# 1급 객체(first-class object)로서의 함수

함수(function)은 객체(object)이다.

* 함수는 별수에 할당(저장)할 수 있음.
* 함수의 argument로 다른 함수를 전달할 수 있음.

In [100]:
# 숫자는 객체(object)다. --> 숫자는 변수에 저장
x =1

In [101]:
print(x) # --> 숫자는 함수의 argument로 전달 할 수 있음.

1

In [102]:
# 함수 정의
def twice(x):
    return 2*x

In [103]:
twice # 함수 호출 아님! twice라는 이름의 객체를 출력한것뿐

In [104]:
twice(2) # 함수 호출.

4

In [105]:
result = twice(3) # 함수 twice()의 호출 결과를 변수 result에 저장.
result

6

In [106]:
double = twice # 함수 twice를 변수 double에 저장.
double

In [107]:
double(3)

6

In [108]:
def calculate(x,y,fn):
    """fn(x,y)의 결과를 리턴.
    @param x:숫자.
    @param y:숫자.
    @param fn:함수.
    """
    result= fn(x,y)
    return result

In [109]:
def plus(x,y):
    return x+y

In [110]:
calculate(1,2,plus)
# > calculate 함수를 호출할 때 파라미터 fn에게 plus 함수를 argument로 전달.

3

In [111]:
def minus(x,y):
    return x-y

In [112]:
calculate(1,2,minus)

-1

# 람다 표현식(Lambda expression)

```
lambda param1, param2, ...: expression
```
* 이름이 없는 함수.
* 함수 이름을 만들지 않고, 함수의 파라미터 선언과 함수의 반환 값(식)만으로 함수를 정의하는 방법.
* 간단하게 정의할 수 있는 함수를 변수(파라미터)에 저장하기 위한 용도

In [61]:
plus_one = lambda x: x+1

In [62]:
plus_one(1)

2

In [63]:
plus = lambda x,y : x+y
 # argument로 x, y를 전달받아서 x + y를 리턴하는 함수

In [64]:
plus(2,4)

6

In [85]:
# 람다 표현식은 argument로 다른 함수에 전달할 수 있음.
calculate(1, 2, lambda x, y: x + y)

3

In [86]:
calculate(1,2,lambda x,y : x-y)

-1

## lambda 식을 argument로 전달받는 함수의 예

* filtering: 전체 데이터에서 조건을 만족하는 데이터만 선택.

In [113]:
numbers = [1,-2,-3,4,5,-6]

In [114]:
# numbers 리스트에서 양수들로만 이루어진 리스트 --> filtering 예
result = filter(lambda x: x>0, numbers)
list(result) #filtering된 결과를 list로 만듦.

[1, 4, 5]

In [115]:
# number 리스트에서 짝수들로만 이루어진 리스트 --> filtering
a = filter (lambda x: x % 2 == 0, numbers)
list(a)

[-2, 4, -6]

* mapping: 여러 데이터를 다른 형태로 변환 / 'Male' --> 0, 'Female'-->1

In [116]:
gender = ['Female','Male','Male','Female']

In [117]:
result = map(lambda x:0 if x == 'Male' else 1,gender)
tuple(result)

(1, 0, 0, 1)

* [0,100] 범위의 정수 10개를 저장하고 있는 리스트에서, 원소가 짝수이면 'even', 홀수이면 'odd'를 갖는 새로운 리스트를 매핑

```
[10,55,90] --> ['even','odd','even']
```

In [118]:
import random

In [119]:
numbers = [random.randrange(100) for _ in range(10)]
numbers

[88, 72, 44, 44, 97, 21, 94, 76, 96, 59]

In [120]:
result = map(lambda x: 'even' if x % 2 == 0 else 'odd', numbers)
list(result)

['even', 'even', 'even', 'even', 'odd', 'odd', 'even', 'even', 'even', 'odd']

In [121]:
# if-else 표현식에서 elif
# 0~ 19 : teen , 20~59: adult, 60 ~ : senior
age = 70
category = 'teen' if 0 <= age < 20 else ('adult' if age <60 else 'senior')
print(category)

senior

In [122]:
age = [random.randrange(100) for _ in range(10)]
age

[85, 93, 22, 31, 8, 26, 3, 80, 12, 67]

In [123]:
result = map(lambda x: 'teen' if x < 20 else ('adult' if x <60 else 'senior'), age)
list(result)

['senior',
 'senior',
 'adult',
 'adult',
 'teen',
 'adult',
 'teen',
 'senior',
 'teen',
 'senior']

## filtering 구현

In [124]:
def my_filter(iterable,fn):
    """iterable의 원소들 중에서 함수 fn의 결과가 True가 되는 
    원소들로 이루어진 리스트를 리턴.
    @param iterable: list, tuple
    @param fn: argument가 1개이고 True 또는 False를 리턴하는 함수.
    """
    # result= [] #필터링된 결과들을 저장할 빈 리스트.
    # for x in iterable: #iterable에서 원소를 1개씩 빼내면서 반복
    #     if fn(x): # 함수 fn()의 리턴값이 True이면
    #         result.append(x) #필터링 결과 리스트에 추가하겠다.
    result = [x for x in iterable if fn(x)] # list comprehension

    return result

In [125]:
numbers =[random.randrange(100) for _ in range(10)]
print(numbers)

result = my_filter(numbers, lambda x: x % 2 == 0) #숫자들 중에서 짝수만 필터링
print(result)

[83, 22, 80, 55, 75, 76, 41, 10, 48, 55]
[22, 80, 76, 10, 48]

In [126]:
age =[random.randrange(100) for _ in range(10)]
print(age)


# age의 원소들 중에서 미성년자(20세 미만)인 데이터들만 필터링
result=my_filter(age, lambda x: x<20 )
print(result)

[55, 89, 83, 3, 34, 27, 90, 8, 63, 83]
[3, 8]

## mapping 구현

In [73]:
def my_mapper1(iterable, fn):
    """iterable의 원소를 함수 fn의 argument로 전달했을 때 그 리턴값들로 이루어진 리스트

    @param iterable: list,tuple.
    @param fn : argument가 1개이고 리턴값을 갖는 함수
    @return : list. [fn(x1), fn(x2), ...]
    """
    result = [fn(x) for x in iterable] #<--list comprehension
    # result=[] 함수 fn()의 리턴값들을 저장할 빈 리스트.
    # for x in iterable: #iterable의 원소들을 하나씩 꺼내서 반복하면서
    #     result.append(fn(x)) #원소(x)를 함수 fn에 전달했을 때 리턴값을 리스트에 추가.
    return result

In [72]:
# my_mapper1 테스트 코드

gender = ['Female','Female','Male','Female','Male']

#'Female' --> 1, 'Male' --> 0

result = my_mapper1(gender,lambda x:0 if x == 'Male' else 1)
list(result)

[1, 1, 0, 1, 0]

In [71]:
# 문자열들의 리스트를 그 문자열의 길이를 갖는 리스트에 mapping
#['abc','apple','안녕하세요!'] --> [3,5,6]

words = ['abc','apple','안녕하세요!']

result = my_mapper1(words, lambda x : len(x))
list(result)

[3, 5, 6]

In [70]:
def my_mapper2(iterable, fn):
    """iterable의 원소를 key로 하고, 그 원소를 함수 fn에 전달했을 때의 리턴값을 value로 하는 dict를 리턴.

    @param iterable: list, tuple.
    @param fn: argument는 1개이고 리턴값이 있는 함수.
    @return: dict. {x1: fn(x1), x2: fn(x2), ...}
    """
    result={x: fn(x) for x in iterable}
    # result={} # key : value를 저장할 빈 리스트.
    # for x in iterable: # iteralbe에서 원소들을 하나씩 꺼내면서 반복
    #     result[x] = fn(x) #iterable에서 꺼낸 원소를 key, 함수 fn()의 리턴값을 values로 한다.

    return result

In [69]:
# my_mapper2() 테스트 코드

packages = ['Numpy','pandas','matplotlib','seaborn','keras','tensorflow']
result = my_mapper2(packages, lambda x:len(x))
print(result)

{'Numpy': 5, 'pandas': 6, 'matplotlib': 10, 'seaborn': 7, 'keras': 5, 'tensorflow': 10}

In [78]:
# [0,100] 범위의 정수 난수 10개를 저장.
# 20 미만인 경우 'A', 60미만인 경우 'B', 60이상인경우에는 'C'를 매핑한 dict

age = [random.randrange(100) for _ in range(10)]
print(age)

result = my_mapper2(age,
                    lambda x: 'A' if x < 20 
                    else ('B' if x<60 else 'C'))
print(result)

[41, 24, 54, 41, 1, 3, 82, 17, 37, 77]
{41: 'B', 24: 'B', 54: 'B', 1: 'A', 3: 'A', 82: 'C', 17: 'A', 37: 'B', 77: 'C'}