* Google Drive에 exam.csv 파일을 업로드
* Colab 연결(세션 활성화)
* Colab에 Google Drive(마운트(mount, 연결)

1. exam.csv 파일을 open
1.파일의 첫번째 줄은 컬럼 이름들이기 때문에, 첫번째 줄은 읽고 무시.
1.파일의 두번째 줄부터 파일 끝(EOF)까지 4번 내용을 반복.
1.각 줄에서 읽은 내용을 쉼표(,)로 분리한 리스트를 빈 리스트에 append.
[['1', '1', '50', '98', '50'], ['2', '1', '60', '97', '60'], ...]

1. 4번에서 만들어진 2차원 리스트는 문자열들을 저장하고 있는 리스트이기 때문에, 리스트의 모든 값들을 정수(int)로 변환
[[1, 1, 50, 98, 50], [2, 1, 60, 97, 60], ...]

1. 수학 점수들로만 이루어진 1차원 리스트를 만듦.
[50, 60, ...]

1. 수학 점수의 최댓값, 최솟값, 평균 출력.
1. 1반 학생들의 수학 점수 총점, 평균, 최댓값, 최솟값 출력

In [43]:
# 읽을 파일의 전체 경로
file_path = '/content/drive/MyDrive/Colab Notebooks/lab_python/exam.csv'

In [ ]:
with open (file_path, mode='rt')as f: # 파일을 read text 모드로 open.
    f.readline() # 파일에서 첫번째 줄을 읽고 아무일도 하지 않음.
    exam = [] # 각 줄에서 읽은 내용을 저장하기 위한 빈 리스트.
    for line in f:  # 위에서 읽은 그 다음줄부터 파일 끝까지 한 줄씩 읽으면서
        exam.append((line.strip().split(sep=',')))

exam

In [106]:
array = ['12', '34', '56']  # --> [12, 34, 56]
for x in array:
    x = int(x)  # array의 원소가 변경되는 것이 아니라, 변수 x의 값이 변경.
print(array)  #> 원본 리스트 array는 아무런 변화가 없음!

['12', '34', '56']

In [107]:
for i, x in enumerate(array):  # enumerate(list): 리스트의 인덱스와 값을 함께 순회함.
    array[i] = int(x)  # 리스트 array에서 꺼낸 값을 int로 변환하고 그 결과를 리스트의 해당 위치에 저장.
print(array)

[12, 34, 56]

In [108]:
array = ['12', '34', '56']
numbers = []
for x in array:
    numbers.append(int(x))

print(array) #원본은 건드리지 않는다.
print(numbers)

['12', '34', '56']
[12, 34, 56]

In [124]:
for row in exam:
    for i, x in enumerate(row):
        row[i]=int(x)
#리스트에 인덱스를 같이 사용하려면 enumerate()
#enumerate()에 리스트를 전달해주면 인덱스와 값을 전달해준다.
exam

[[1, 1, 50, 98, 50],
 [2, 1, 60, 97, 60],
 [3, 1, 45, 86, 78],
 [4, 1, 30, 98, 58],
 [5, 2, 25, 80, 65],
 [6, 2, 50, 89, 98],
 [7, 2, 80, 90, 45],
 [8, 2, 90, 78, 25],
 [9, 3, 20, 98, 15],
 [10, 3, 50, 98, 45],
 [11, 3, 65, 65, 65],
 [12, 3, 45, 85, 32],
 [13, 4, 46, 98, 65],
 [14, 4, 48, 87, 12],
 [15, 4, 75, 56, 78],
 [16, 4, 58, 98, 65],
 [17, 5, 65, 68, 98],
 [18, 5, 80, 78, 90],
 [19, 5, 89, 68, 87],
 [20, 5, 78, 83, 58]]

In [125]:
# math=[] # 수학 점수들을 저장할 빈 리스트.
# for row in exam:
#     math.append(row[2]) # 1차원 리스트에서 인덱스 2번 위치의 원소가 수학점수.
math = [row[2] for row in exam]

print(math)

[50, 60, 45, 30, 25, 50, 80, 90, 20, 50, 65, 45, 46, 48, 75, 58, 65, 80, 89, 78]

In [126]:
print(f'max:',max(math))
print(f'min:',min(math))
mean= sum(math)/len(math)
print(f'mean:',mean)

max: 90
min: 20
mean: 57.45

In [127]:
# 데이터가 id -> class 순서로 정렬되어 있고, 1반의 학생수가 4명인 것을 아는 경우:
class1_math = math[:4]
print(class1_math)

[50, 60, 45, 30]

In [128]:
# 데이터가 무작위로 섞여 있는 경우:
class1_math = []  # 1반 학생들의 수학 점수를 저장할 빈 리스트.
for row in exam:
    if row[1] == 1:  # class값이 1이면
        class1_math.append(row[2])  # 수학 점수를 리스트에 추가.

print(class1_math)

[50, 60, 45, 30]

In [129]:
math_class1 = [row[2] for row in exam if row[1] == 1]
print(math_class1)

[50, 60, 45, 30]

In [100]:
print(f'1반 수학 최댓값:', max(math_class1))
print(f'1반 수학 최솟값:', min(math_class1))
print(f'1반 수학 합계:', sum(math_class1))
print(f'1반 수학 평균:', sum(math_class1)/len(math_class1))
type(math_class1)

1반 수학 최댓값: 60
1반 수학 최솟값: 30
1반 수학 합계: 185
1반 수학 평균: 46.25

list

# Pandas 패키지

* 행, 열 1차원 컬럼 = series
* 2차원 = DF(데이터프레임)

In [87]:
import pandas as pd

In [88]:
exam_df = pd.read_csv(file_path) # CSV 파일을 읽어서 DataFrame을 생성.
type(exam_df)

pandas.core.frame.DataFrame

In [ ]:
print(exam_df)

In [ ]:
exam_df

In [133]:
# DataFrame에서 math 컬럼을 선택
math =exam_df['math']

In [134]:
math.sum() # 합계

1149

In [136]:
math.count()  # math 컬럼의 원소 개수

20

In [102]:
math.mean()  # 평균

57.45

In [97]:
math.max() # 최댓값

90

In [98]:
math.min() # 최솟값

20

In [99]:
# 1반 학생들 DataFrame
class1 = exam_df[exam_df['class']==1]
class1

   id  class  math  english  science
0   1      1    50       98       50
1   2      1    60       97       60
2   3      1    45       86       78
3   4      1    30       98       58

In [142]:
class1_math=class1['math']
class1_math

0    50
1    60
2    45
3    30
Name: math, dtype: int64

In [143]:
#파이썬에서는 mean 함수가 없지만, 판다스에는 평균을 구하는 함수가 있다.

In [144]:
class1_math.describe()
# 기술 통계량(개수, 평균, 표준편차, ...) - R에서 summary() 함수

count     4.00
mean     46.25
std      12.50
min      30.00
25%      41.25
50%      47.50
75%      52.50
max      60.00
Name: math, dtype: float64